---

- name: Fail if required Chatgpt settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'matrix_bot_chatgpt_openai_api_key', when: true}
    - {'name': 'matrix_bot_chatgpt_matrix_bot_username', when: true}


- name: Fail if OpenAI configuration not up-to-date.
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a varible that is no longer used.
      Please change your configuration to remove the variable (`{{ item.name }}`).
  when: "item.name in vars"
  with_items:
    - {'name': 'matrix_bot_chatgpt_openai_email'}
    - {'name': 'matrix_bot_chatgpt_openai_password'}
    - {'name': 'matrix_bot_chatgpt_openai_login_type'}
