---

- name: Fail if Synapse metrics or Prometheus Node Exporter not enabled
  ansible.builtin.fail:
    msg: >
      You need to enable `matrix_prometheus_scraper_synapse_enabled` and/or `matrix_prometheus_scraper_node_enabled` for Prometheus grab metrics.
  when: "not matrix_prometheus_scraper_synapse_enabled and not matrix_prometheus_scraper_node_enabled"

- name: Fail if required Prometheus settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - matrix_prometheus_container_network
