---
#
# Tasks related to configuring Jitsi internal authentication on a running prosody instance.
#

- name: Ensure Jitsi internal authentication users are configured
  ansible.builtin.shell: "{{ devture_systemd_docker_base_host_command_docker }} exec matrix-jitsi-prosody prosodyctl --config /config/prosody.cfg.lua register {{ item.username | quote }} meet.jitsi {{ item.password | quote }}"
  with_items: "{{ matrix_jitsi_prosody_auth_internal_accounts }}"
  when:
    - matrix_jitsi_prosody_auth_internal_accounts|length > 0
  register: matrix_jitsi_user_configuration_result
  changed_when: matrix_jitsi_user_configuration_result.rc == 0
  no_log: true

#
# Tasks related to clean up after configuring internal authentication.
#
